//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OttomanStone.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int BannerAlanID { get; set; }
        public string BannerAdi { get; set; }
        public Nullable<int> BannerW { get; set; }
        public Nullable<int> BannerY { get; set; }
        public Nullable<int> BannerMaxTik { get; set; }
        public Nullable<int> Siralama { get; set; }
    }
}
