//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OttomanStone.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Queue { get; set; }
        public Nullable<int> TopId { get; set; }
        public Nullable<int> LangId { get; set; }
        public string Link { get; set; }
        public Nullable<int> Yayin { get; set; }
        public string KategoriIcon { get; set; }
        public string KategoriResim { get; set; }
        public Nullable<bool> OzelFiltre { get; set; }
    }
}
