//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OttomanStone.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class content
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Contents { get; set; }
        public string Link { get; set; }
        public Nullable<int> CatId { get; set; }
        public Nullable<int> LangId { get; set; }
        public Nullable<int> Queue { get; set; }
        public Nullable<int> Yayin { get; set; }
        public Nullable<bool> TamSayfa { get; set; }
        public Nullable<bool> OzellikYeniUrun { get; set; }
        public Nullable<bool> OzellikOzelTasarimUrun { get; set; }
        public Nullable<bool> OzellikUrunSatildi { get; set; }
        public Nullable<bool> UrunSayfasi { get; set; }
        public string UrunKodu { get; set; }
        public string UrunFiyat { get; set; }
    }
}
