//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OttomanStone.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KategoriOzellikleri
    {
        public int KatagoriOzellikID { get; set; }
        public Nullable<int> KatagoriOzellikKategoriID { get; set; }
        public string KatagoriOzellikAdi { get; set; }
        public string KatagoriOzellikAciklama { get; set; }
        public Nullable<bool> KatagoriOzellikDurum { get; set; }
        public Nullable<int> KatagoriOzellikSira { get; set; }
        public Nullable<bool> KategoriOzellikleriTekSecim { get; set; }
        public Nullable<bool> KategoriOzellikleriIsTextBox { get; set; }
        public Nullable<bool> KategoriOzellikleriSuzmedeKullan { get; set; }
        public Nullable<int> KatagoriOzellikEkleyen { get; set; }
        public Nullable<System.DateTime> KatagoriOzellikEklenme { get; set; }
        public Nullable<int> KatagoriOzellikDuzenleyen { get; set; }
        public Nullable<System.DateTime> KatagoriOzellikDuzenleme { get; set; }
    }
}
