//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OttomanStone.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategoriler
    {
        public int KategoriID { get; set; }
        public string KategoriAdi { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public string KategoriIcon { get; set; }
        public string KategoriResim { get; set; }
        public Nullable<bool> KategoriDurum { get; set; }
        public Nullable<int> KategoriSira { get; set; }
        public Nullable<int> KategoriUstKat { get; set; }
        public string KategoriAdi_Kucuk { get; set; }
        public Nullable<bool> OzelFiltre { get; set; }
        public string KategoriAciklama { get; set; }
        public Nullable<int> KategoriEkleyen { get; set; }
        public Nullable<System.DateTime> KategoriEklenme { get; set; }
        public Nullable<int> KategoriDuzenleyen { get; set; }
        public Nullable<System.DateTime> KategoriDuzenleme { get; set; }
    }
}
