//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OttomanStone.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KategoriOzellikSecenekleri
    {
        public int KatagoriOzellikSecenekleriID { get; set; }
        public string KatagoriOzellikSecenekleriDeger { get; set; }
        public Nullable<int> KatagoriOzellikSecenekleriKatagoriOzellikID { get; set; }
        public Nullable<bool> KatagoriOzellikSecenekleriSil { get; set; }
    }
}
