//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OttomanStone.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OttomanStoneEntities : DbContext
    {
        public OttomanStoneEntities()
            : base("name=OttomanStoneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Banner> Banner { get; set; }
        public DbSet<BannerReklam> BannerReklam { get; set; }
        public DbSet<category> categorie { get; set; }
        public DbSet<ContentImage> ContentImage { get; set; }
        public DbSet<content> contents { get; set; }
        public DbSet<Kategoriler> Kategoriler { get; set; }
        public DbSet<KategoriOzellikleri> KategoriOzellikleri { get; set; }
        public DbSet<KategoriOzellikSecenekleri> KategoriOzellikSecenekleri { get; set; }
        public DbSet<language> language { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<View_BannerBannerReklam> View_BannerBannerReklam { get; set; }
        public DbSet<View_ContentCategoryContentImages> View_ContentCategoryContentImages { get; set; }
    }
}
