//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OttomanStone.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ContentCategoryContentImages
    {
        public string KategoriAdi_Kucuk { get; set; }
        public string Title { get; set; }
        public string Contents { get; set; }
        public string Link { get; set; }
        public string ContentImage { get; set; }
        public int Id { get; set; }
        public Nullable<int> ContentId { get; set; }
    }
}
