//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OttomanStone.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_BannerBannerReklam
    {
        public Nullable<int> BannerReklamBannerID { get; set; }
        public string BannerReklamUrl { get; set; }
        public string BannerReklamDeger { get; set; }
        public Nullable<System.DateTime> BannerReklamBaslangic { get; set; }
        public Nullable<System.DateTime> BannerReklamBitis { get; set; }
        public Nullable<long> BannerReklamGosterim { get; set; }
        public Nullable<long> BannerReklamTiklanma { get; set; }
        public Nullable<int> BannerReklamMaxTik { get; set; }
        public string BannerReklamBaslik { get; set; }
        public string BannerReklamDetay { get; set; }
        public Nullable<int> BannerReklamSiralama { get; set; }
        public string BannerAdi { get; set; }
        public Nullable<int> BannerW { get; set; }
        public Nullable<int> BannerY { get; set; }
        public Nullable<int> Siralama { get; set; }
        public int BannerAlanID { get; set; }
    }
}
